#!/bin/bash

function get_plist_path {
	echo "# Retrieve a plist path for \"$1\" ..." 1>&2
	plist_path=$(/usr/bin/xcrun xcodebuild -showBuildSettings -target $1 2>/dev/null | grep "INFOPLIST_FILE" | sed 's/[ ]*INFOPLIST_FILE = //')
	if [ -z "$plist_path" ]; then
		echo "[!] Not found plist of given target. \"$1\"" 1>&2; exit 1; return 0;
	fi
	echo $plist_path
}
function check_conflict {
	if $(git status --porcelain | grep UU); then
	    echo Repo was Confilcted.; exit 1
	fi
}
function check_clean {
	if [ -n "$(git ls-files --others --exclude-standard)" ]; then
		echo Repo was NOT Cleaned.; exit 1
	fi
}
tmp_stash_id="stash_id_tmp"
function get_tmp_stash_id {
	echo "$(git stash list | grep $tmp_stash_id | awk -F':' '{print $1}' | head -1)"
}
current_branch="$(git rev-parse --abbrev-ref HEAD)"
check_conflict
git stash save -u $tmp_stash_id
check_clean
git pull origin $current_branch
check_conflict
echo "# Cleaned. Now start tasks ..."

echo "# Retrieve submitted tag ..."
plist_path=$(/usr/bin/xcrun xcodebuild -showBuildSettings -target $1 2>/dev/null | grep "INFOPLIST_FILE" | sed 's/[ ]*INFOPLIST_FILE = //')
if [ -z "$plist_path" ]; then
	echo "[!] Not found plist of given target. $1"; exit 1
fi
VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$plist_path")
if [ -z "$VERSION" ]; then
	echo "[!] Not Found CFBundleShortVersionString for given project target. $1"; exit 1
fi
lastest_submitted_tag_name=$(git describe --abbrev=0 --tags --match "$1"/submit/"$VERSION"*)
if [ -z "$lastest_submitted_tag_name" ]; then
	echo "[!] Not Found lastest submitted tag "$1"/submit/"$VERSION". Try 'git xcp submit $1' first."; exit 1
fi
release_tag_name="$1/$VERSION"
git checkout $lastest_submitted_tag_name
git tag $release_tag_name
git checkout master
git pull origin master
check_conflict
echo "# Now merging ..."
git merge --allow-unrelated-histories --squash -X theirs $lastest_submitted_tag_name
echo "# Now deploy to origin : $release_tag_name ..."
git add . && git commit -m "[Release $release_tag_name]" && git push origin master
git checkout $current_branch
git push origin $release_tag_name

# undo stash
tmp_stash_id=$(get_tmp_stash_id)
if [ -n "$tmp_stash_id" ]; then
	if [ -n "$(git stash pop "$tmp_stash_id" --index | egrep "Dropped $tmp_stash_id")" ]; then
		echo "Restored working directory and index state succesfully."
	fi
fi
echo "# Done."
