#!/bin/bash
source $(dirname $0)/xcp-shared
check_complict
git stash save -u $STASH_ID
check_clean
git pull origin $CURRENT_BRANCH
check_complict
echo "============ CLEANED. NOW START TASK... ============"