#!/bin/bash

function check_complict {
	if $(git status --porcelain | grep UU); then
	    echo Repo was Confilcted.; exit 1
	fi
}
function check_clean {
	if [ -n "$(git ls-files --others --exclude-standard)" ]; then
		echo Repo was NOT Cleaned.; exit 1
	fi
}
STASH_ID="stash_id_tmp"
function get_tmp_stash_id {
	echo "$(git stash list | grep $STASH_ID | awk -F':' '{print $1}' | head -1)"
}
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

check_complict
git stash save -u $STASH_ID
check_clean
git pull origin $CURRENT_BRANCH
check_complict
echo "============ CLEANED. NOW START TASK... ============"


echo "============ RERRIEVE SUBMITTED TAG... ============"
plist_path=$(/usr/bin/xcrun xcodebuild -showBuildSettings -target $1 2>/dev/null | grep "INFOPLIST_FILE" | sed 's/[ ]*INFOPLIST_FILE = //')
if [ -z "$plist_path" ]; then
	echo "[!] Not found plist of given target. $1"; exit 1
fi
VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$plist_path")  
if [ -z "$VERSION" ]; then
	echo "[!] Not Found CFBundleShortVersionString for given project target. $1"; exit 1
fi
LASTEST_SUBMITTED_TAG_NAME=$(git describe --abbrev=0 --tags --match "$1"/submit/"$VERSION"*)
if [ -z "$LASTEST_SUBMITTED_TAG_NAME" ]; then
	echo "[!] Not Found lastest submitted tag. Matching format: "$1"/submit/"$VERSION"* "; exit 1
fi
RELEASE_TAG="$1/$VERSION"

git checkout $LASTEST_SUBMITTED_TAG_NAME
git tag $RELEASE_TAG

git checkout master
git pull origin master
check_complict
echo "============ NOW MERGING... ============"
git merge --squash -X theirs $LASTEST_SUBMITTED_TAG_NAME
echo "============ NOW DEPLOY TO ORIGIN : $RELEASE_TAG ============"
git add . && git commit -m "[Release $RELEASE_TAG]" && git push origin master
git checkout $CURRENT_BRANCH

git push origin $RELEASE_TAG

# undo stash
STASHED_ID=$(get_tmp_stash_id)
if [ -n "$STASHED_ID" ]; then
	if [ -n "$(git stash pop "$STASHED_ID" --index | egrep "Dropped $STASHED_ID")" ]; then
		echo "Restored working directory and index state succesfully."
	fi
fi
echo "============ DONE. ============"
