#!/bin/bash
PATT_RM='sed -E s/(^#\!\/bin\/bash|^source.+$)//g'
TARGET_DIR=$(dirname $0)

echo '#!/bin/bash' > $TARGET_DIR/$1
cat $TARGET_DIR/src/xcp-begin | $PATT_RM >> $TARGET_DIR/$1 \
&& cat $TARGET_DIR/src/$1-src | $PATT_RM >> $TARGET_DIR/$1 \
&& cat $TARGET_DIR/src/xcp-end | $PATT_RM >> $TARGET_DIR/$1
echo "$TARGET_DIR/$1"
sudo chmod 755 $TARGET_DIR/$1
