#!/bin/bash

function check_complict {
	if $(git status --porcelain | grep UU); then
	    echo Repo was Confilcted.; exit 1
	fi
}
function check_clean {
	if [ -n "$(git ls-files --others --exclude-standard)" ]; then
		echo Repo was NOT Cleaned.; exit 1
	fi
}
STASH_ID="stash_id_tmp"
function get_tmp_stash_id {
	echo "$(git stash list | grep $STASH_ID | awk -F':' '{print $1}' | head -1)"
}
CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"


check_complict
git stash save -u $STASH_ID
check_clean
git pull origin $CURRENT_BRANCH
check_complict
echo "============ CLEANED. NOW START TASK... ============"



plist_path=$(/usr/bin/xcrun xcodebuild -showBuildSettings -target $1 2>/dev/null | grep "INFOPLIST_FILE" | sed 's/[ ]*INFOPLIST_FILE = //')
if [ -z "$plist_path" ]; then
	echo "[!] Not found plist of given target. $1"; exit 1
fi
if [ -z "$2" ]; then
	echo "[!] Please provide CFBundleShortVersionString (Marketing version). $1"; exit 1
fi
/usr/libexec/PlistBuddy -c "Set CFBundleShortVersionString $2" $plist_path
git add . && git commit -m "[Open - $1 - $2]" && git push origin $CURRENT_BRANCH
echo $2

# undo stash
STASHED_ID=$(get_tmp_stash_id)
if [ -n "$STASHED_ID" ]; then
	if [ -n "$(git stash pop "$STASHED_ID" --index | egrep "Dropped $STASHED_ID")" ]; then
		echo "Restored working directory and index state succesfully."
	fi
fi
echo "============ DONE. ============"
