#!/bin/bash
source $(dirname $0)/xcp-begin

plist_path=$(get_plist_path "$1") || exit 1;
VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "$plist_path")
BUILD_NUM=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$plist_path")

latest_built_tag_name=$(git describe --abbrev=0 --tags --match "$TARGET"/beta/b"$BUILD_NUM")
if [ -z "$latest_built_tag_name" ]; then
	echo "[!] Not Found the latest built tag "$TARGET"/beta/b"$BUILD_NUM". Try 'git xcp beta $TARGET' first."; exit 1
fi

git checkout $latest_built_tag_name

TARGET_TAG="$TARGET"/submit/"$VERSION"_b"$BUILD_NUM"
TARGET_BRANCH=release-submit-"$TARGET"

git branch $TARGET_BRANCH $latest_built_tag_name -f && \
git checkout $TARGET_BRANCH && \
git push -f origin $TARGET_BRANCH && \
git tag "$TARGET_TAG" -f && \
git push origin "$TARGET_TAG" -f

git checkout $current_branch

source $(dirname $0)/xcp-end
